userconfig:
  # Options: 
  # "no-build" or "editor" for manual mode. Runs in Unity editor.
  # "build" mode to run with pre build unity version.
  mode: build
  # "test" mode bypasses ml-agents execution. Must be bool.
  test: false
  # Provide message for the log file for better traceability.
  message: "Test collision handling. Based on run 221 config."
behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: [128, 256]
      buffer_size: 10240
      learning_rate: 1e-3
      beta: 1e-3
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: [128, 256, 384]
      num_layers: [3, 4]
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000