userconfig:
  # Options: no-build for manual mode. Runs in Unity editor.
  mode: build
behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: [10240, 128000, 256000]
      learning_rate: [1e-5, 1e-4, 1e-3]
      beta: [1e-2, 5e-3, 1e-3, 5e-2]
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: [128, 256, 384]
      num_layers: 2
      memory:
        memory_size: [128, 256]
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1e6
    time_horizon: 64
    summary_freq: 10000