userconfig:
  # Use build env? Set false for run using the unity editor.
  build: false

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 1

  # Production mode? Bool requiered. Set to false if ml-agents is not to be run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Set to false to delete all files after the programm finishes.
  keep_files: true

  # Provide message for the log file for better traceability.
  message: "Decoy further training. 512 hidden units."

  # Initialize from existing previous run.
  based_on_previous_nn: false
  previous_run_id: 1080

behaviors:
  RollerAgent:
    # Common Trainer Configurations.
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 30e6
    time_horizon: 1000
    summary_freq: 10000

    hyperparameters:
      # Common Trainer Configurations.
      batch_size: 512
      buffer_size: 204800
      learning_rate: 1e-3
      learning_rate_schedule: linear

      # PPO-specific Configurations.
      #beta: 0.0025
      beta: 0.0025
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2
      
    network_settings:
      conditioning_type: none # Can be none, because no goal observation is used.
      normalize: false
      hidden_units: 512
      num_layers: 1
      memory:
        memory_size: 128
        sequence_length: 64
      #vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
      #  strength: 1.5
      #  gamma: 0.99
      #  learning_rate: 3e-4
      #  network_settings: 
      #    hidden_units: 512
      
    


    
