userconfig:
  # Use build env? false for editor.
  build: false

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 1

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Set to false to delete all files after the programm finishes.
  keep_files: false

  # Provide message for the log file for better traceability.
  message: "Sparse reward. Reduced observations by the agent. No maxstep. No wall. Try to overfit. Curiosty."

behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 102400
      learning_rate: 1e-4
      beta: 2.5e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      #conditioning_type: none
      normalize: false
      hidden_units: 256
      num_layers: 0
      memory:
        memory_size: 128
        sequence_length: 64
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
      #  strength: 0.5
      #  gamma: 0.99
      #  learning_rate: 3e-4
      #  network_settings: 
      #    hidden_units: 512
    keep_checkpoints: 5
    max_steps: 0.3e6
    time_horizon: 1000
    summary_freq: 10000
