userconfig:
  # Use build env? false for editor.
  build: true

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 2

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Set to false to delete all files after the programm finishes.
  #keep_files: true

  # Provide message for the log file for better traceability.
  message: "Check for numpy errors with new venv."

behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: [10240, 20480]
      learning_rate: 1e-3
      beta: 5e-3
      epsilon: 0.2
      lambd: 9.25
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory:
        memory_size: 64
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 0.5e6
    time_horizon: 128
    summary_freq: 10000