userconfig:
  # Options: 
  # "no-build" or "editor" for manual mode. Runs in Unity editor.
  # "build" mode to run with pre build unity version.
  # "test" mode bypasses ml-agents execution.
  mode: build
behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 246
      buffer_size: 10240
      learning_rate: [1e-4, 1e-5]
      beta: 1e-3
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: [128, 384]
      num_layers: [2, 3]
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000