userconfig:
  # Use build env? false for editor.
  build: true

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 1

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Set to false to delete all files after the programm finishes.
  keep_files: true

  # Provide message for the log file for better traceability.
  message: "Rerun of 789. Build and 8 training areas. Punish each step. Research epsilon."

behaviors:
  RollerAgent:
    # Common Trainer Configurations.
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 1e6
    time_horizon: 1000
    summary_freq: 10000

    hyperparameters:
      # Common Trainer Configurations.
      batch_size: 64
      buffer_size: 50120
      learning_rate: 1e-3
      learning_rate_schedule: linear

      # PPO-specific Configurations.
      beta: 5e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2
      
    network_settings:
      conditioning_type: none # Can be none, because no goal observation is used.
      normalize: false
      hidden_units: 256
      num_layers: 0
      memory:
        memory_size: 128
        sequence_length: 32
      #vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
      #  strength: 0.5
      #  gamma: 0.99
      #  learning_rate: 3e-4
      #  network_settings: 
      #    hidden_units: 512
    
