userconfig:
  # Use build env? false for editor.
  build: false

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 1

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Provide message for the log file for better traceability.
  message: "SAC test."

behaviors:
  RollerAgent:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 10240
      learning_rate: 1e-5
      #beta: 5e-3
      #epsilon: 0.2
      #lambd: 0.925
      #num_epoch: 3
      learning_rate_schedule: linear
      #beta_schedule: constant
      #epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory:
        memory_size: [64, 128]
        sequence_length: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 0.5e6
    time_horizon: 128
    summary_freq: 10000