userconfig:
  # Use build env? false for editor.
  build: true

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 1

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Set to false to delete all files after the programm finishes.
  keep_files: true

  # Provide message for the log file for better traceability.
  message: "No inner wall. Test gail with bc. Shorter runs. Expert trainer provided by NN from run 948. Parameter search with good expert data."

behaviors:
  RollerAgent:
    # Common Trainer Configurations.
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 5e6
    time_horizon: 1000
    summary_freq: 10000

    hyperparameters:
      # Common Trainer Configurations.
      batch_size: 512
      buffer_size: 102400
      learning_rate: 1e-3
      learning_rate_schedule: linear

      # PPO-specific Configurations.
      #beta: 0.0025
      beta: 0.0025
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2
      
    network_settings:
      conditioning_type: none # Can be none, because no goal observation is used.
      normalize: false
      hidden_units: 256
      num_layers: 0
      memory:
        memory_size: 128
        sequence_length: 64
      #vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
      #  strength: 1.5
      #  gamma: 0.99
      #  learning_rate: 3e-4
      #  network_settings: 
      #    hidden_units: 512
      gail:
        demo_path: C:\Users\max.muehlefeldt\Documents\GitHub\unity-machine-learning\python\basic_rl_env\demonstrations\948NoDoor.demo
        #demo_path: C:\Users\max.muehlefeldt\Documents\GitHub\unity-machine-learning\python\basic_rl_env\demonstrations\FixedWallDoor.demo
        strength: [0.01, 0.08, 0.1, 0.2]
        gamma: 0.99
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
    behavioral_cloning:
      demo_path: C:\Users\max.muehlefeldt\Documents\GitHub\unity-machine-learning\python\basic_rl_env\demonstrations\948NoDoor.demo
      steps: [500000, 1000000, 1500000, 2500000]
      strength: [0.5, 0.7, 1.0]




    
