userconfig:
  # Use build env? false for editor.
  build: true

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true
  num_env: 2

  # Provide message for the log file for better traceability.
  message: "Runs over night."

behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: [64, 128, 256]
      buffer_size: [10240, 51200, 102400, 204800]
      learning_rate: [1e-5, 1e-4, 1e-3]
      beta: 5e-3
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: [128, 256, 384]
      num_layers: 4
      memory:
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1e6
    time_horizon: 128
    summary_freq: 10000