behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 10240
      learning_rate: 1e-3
      beta: 1e-2
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      memory:
        memory_size: [32, 64, 128]
        sequence_length: [16, 32, 64, 128]
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1e6
    time_horizon: 64
    summary_freq: 10000