userconfig:
  # Use build env? false for editor.
  build: true

  # Specify number of parallel env to use.
  num_env: 1

  # Number of parallel processes.
  num_process: 1

  # Production mode? false for test run.
  production: true

  # "true" to generate summary file.
  summary: true

  # Set to false to delete all files after the programm finishes.
  keep_files: true

  # Provide message for the log file for better traceability.
  message: "Check for numpy errors."

behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 409600
      learning_rate: 1e-3
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      memory:
        memory_size: 64
        sequence_length: 64
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 2e6
    time_horizon: 1000
    summary_freq: 10000
