behaviors:
  RollerAgent:
    trainer_type: ppo
    hyperparameters:

      batch_size: 512
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1e-2
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      #memory:
        #memory_size: 128
        #sequence_length: 10
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 6e6
    time_horizon: 64
    summary_freq: 10000