behaviors:
  DroneAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240

      # (default = 3e-4)
      # Initial learning rate for gradient descent.
      # Corresponds to the strength of each gradient descent update
      # step. This should typically be decreased if training is unstable,
      # and the reward does not consistently increase. 
      learning_rate: 1.0e-5

      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false

      # (default = 128)
      # Number of units in the hidden layers of the neural network.
      # Correspond to how many units are in each fully connected layer of the neural network.
      # For simple problems where the correct action is a straightforward combination of the observation inputs, this should be small.
      # For problems where the action is a very complex interaction between the observation variables, this should be larger.
      # Typical range: 32 - 512
      hidden_units: 512
      num_layers: 8
      memory:
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5e6
    time_horizon: 64
    summary_freq: 10000